#!/bin/bash

# Fail loudly
set -e

app_root=/var/www/townstage.com
current="$app_root/releases/$(date +"%Y%m%d%H%M")"

# Set up environmental variables
unset GIT_DIR
export `cat $app_root/shared/.env`

# Get rid of 'remote: ' text that git appends to output
pretty_print() {
  echo -e "\033[G$@\033[K"
}

mkdir -pv $current
git archive master | tar -x -C $current

for shared in config/database.yml config/puma.rb .env log public/assets public/uploads tmp vendor/bundle db/backups
do
rm -rf $current/$shared
ln -nsf $app_root/shared/$shared $current/$shared
done

cd $current

source /etc/profile.d/chruby.sh
chruby `cat .ruby-version`

bundle exec sidekiqctl quiet tmp/sidekiq.pid

bundle install --without development:test --binstubs vendor/bundle/bin --deployment
bundle exec rake db:migrate
bundle exec rake assets:precompile
bundle exec whenever --write-crontab

ln -nsf $current $app_root/current

test -s tmp/puma.pid && kill -USR2 `cat tmp/puma.pid`
bundle exec sidekiqctl stop tmp/sidekiq.pid 60

pretty_print
pretty_print "Ladies and gentlemen, we have successfully deployed to Linode!"
pretty_print
